### PR TITLE
Create sqlalchemy_usage.py

### PR DESCRIPTION
**Pull request by ferid333**
Create sqlalchemy_usage.py

### CODE REVIEW

**Comment by wigging** [comment]
Hello. Are you trying to submit an example to this repository?

**Comment by ferid333** [comment]
Hi. I add new script to python scripts to show usage of sqlalchemy library

**Comment by wigging** [comment]
Can you also provide a markdown file in the content directory that explains what the code does?

**Comment by ferid333** [comment]
Where should I exactly add this markdown file ?

**Comment by wigging** [comment]
In the content directory at `pythonic/content/`. See the other markdown files in that directory for examples.

**Comment by ferid333** [comment]
I added

**Comment by wigging** [comment]
Still need to add the proper heading to the file. This is from the `pythonic/content/python/argparse.md`:

```text
---
title: Argparse
date: September 28, 2024
---
```

**Comment by ferid333** [comment]
I made

**Comment by wigging** [comment]
Thanks. I'll look at the changes later today.

**Comment by ferid333** [comment]
You are welcome

**Pull request closed without merging**
